force-app/main/default/objects/Account/fields/BlockComm__c.field-meta.xml
<CustomField>
    <fullName>BlockComm__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bloquear envío de marketing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CardType__c.field-meta.xml
<CustomField>
    <fullName>CardType__c</fullName>
    <defaultValue>&quot;C&quot;</defaultValue>
    <label>Clase de socio de negocios</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Condici_n_de_pago_EM__c.field-meta.xml
<CustomField>
    <fullName>Condici_n_de_pago_EM__c</fullName>
    <label>Condición de pago EM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30 días Precio Contado</fullName>
            </value>
            <value>
                <fullName>60 Días sin Intereses</fullName>
            </value>
            <value>
                <fullName>90 Días sin Intereses</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30 y 45 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 30% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 30% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40%, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40%, Cheques 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo contra entrega</fullName>
            </value>
            <value>
                <fullName>Anticipo 50%, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 50% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 50% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 50% saldo contra entrega</fullName>
            </value>
            <value>
                <fullName>Anticipo 60% saldo 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 70%, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 70%, Cheques 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 70%, Cheques 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Cheque adjunto 30, 60 y 90 días</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CondicionPago__c.field-meta.xml
<CustomField>
    <fullName>CondicionPago__c</fullName>
    <label>Condición de pago GE</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30 días Precio Contado</fullName>
            </value>
            <value>
                <fullName>60 Días sin Intereses</fullName>
            </value>
            <value>
                <fullName>90 Días sin Intereses</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30 y 45 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 30% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 30% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40%, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40%, Cheques 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo contra entrega</fullName>
            </value>
            <value>
                <fullName>Anticipo 50%, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 50% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 50% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 50% saldo contra entrega</fullName>
            </value>
            <value>
                <fullName>Anticipo 60% saldo 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 70%, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 70%, Cheques 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 70%, Cheques 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Cheque adjunto 30, 60 y 90 días</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>&quot;CL&quot;</defaultValue>
    <label>País</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CreditLine__c.field-meta.xml
<CustomField>
    <fullName>CreditLine__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Límite de crédito</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DebtLine__c.field-meta.xml
<CustomField>
    <fullName>DebtLine__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Límite de deuda</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>Campo requerido para sincronizar con SAP</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/EstadoSAP__c.field-meta.xml
<CustomField>
    <fullName>EstadoSAP__c</fullName>
    <label>Estado SAP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Creado sin validar</fullName>
                <default>true</default>
                <label>Creado sin validar</label>
            </value>
            <value>
                <fullName>Validado por SAP</fullName>
            </value>
            <value>
                <fullName>No Validado por SAP</fullName>
            </value>
            <value>
                <fullName>Cliente Inactivo en SAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Giro__c.field-meta.xml
<CustomField>
    <fullName>Giro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Campo requerido para sincronizar con SAP</inlineHelpText>
    <label>Giro</label>
    <referenceTo>Giro__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/GroupCode__c.field-meta.xml
<CustomField>
    <fullName>GroupCode__c</fullName>
    <label>Código de grupo</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/NombreFantasia__c.field-meta.xml
<CustomField>
    <fullName>NombreFantasia__c</fullName>
    <label>Nombre Fantasía</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RUT_DV__c.field-meta.xml
<CustomField>
    <fullName>RUT_DV__c</fullName>
    <description>Dígito verificador</description>
    <label>DV</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RUT_SD__c.field-meta.xml
<CustomField>
    <fullName>RUT_SD__c</fullName>
    <label>RUT (sin dígito)</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SlpCode__c.field-meta.xml
<CustomField>
    <fullName>SlpCode__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Se debe pasar un valor por defecto de un usuario &quot;comodín&quot; ingresado en SAP, por el momento pasaremos el valor &quot;1&quot;</description>
    <label>Código del empleado de ventas</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Lureye_ActualizaCuentasDesdeSAPBatch.cls
global class Lureye_ActualizaCuentasDesdeSAPBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext info){ 
        String query=' SELECT  Id, CondicionPago__c, ParentId, Description, ShippingAddress, Condici_n_de_pago_EM__c,' +
                            ' BillingAddress, NumberOfEmployees, Fax, Giro__c, Industry,Name, ' +
                            ' Ownership,RUT_SD__c, Website, Phone, Type, CardType__c, GroupCode__c, ' +
                            ' CreditLine__c, DebtLine__c, SlpCode__c, CurrencyIsoCode, Country__c, NombreFantasia__c, ' +
                            ' BlockComm__c, RUT_DV__c, Email__c,EstadoSAP__c ' +
                    ' FROM    Account ' +
                    ' WHERE RUT_SD__c != null ';    
        System.debug('query->' + query);
        return Database.getQueryLocator(query); 
    }     

    //Ejecuta por lotes
    global void execute(Database.BatchableContext info, List<Account> scope){
        List<Account> listaUpd = new List<Account>();
        for(Account acc : scope){
            Boolean flag = false;
            //electromecanica
            SL_Client_JSON clienteSAP = ConsultaClienteSAP(String.valueof(acc.RUT_SD__c), 'loginEM');
            if(clienteSAP != null && clienteSAP.paytermsgrpcode != null){
                if(acc.Condici_n_de_pago_EM__c != LUREYE_SAP_Controller.switchIntCondition(clienteSAP.paytermsgrpcode)){
                    acc.Condici_n_de_pago_EM__c  = LUREYE_SAP_Controller.switchIntCondition(clienteSAP.paytermsgrpcode);
                    flag = true;
                }               
            }
            //Generacion
            clienteSAP = ConsultaClienteSAP(String.valueof(acc.RUT_SD__c), 'loginGE');
            if(clienteSAP != null && clienteSAP.paytermsgrpcode != null){
                if(acc.CondicionPago__c != LUREYE_SAP_Controller.switchIntCondition(clienteSAP.paytermsgrpcode)){
                    acc.CondicionPago__c  = LUREYE_SAP_Controller.switchIntCondition(clienteSAP.paytermsgrpcode);
                    flag = true;
                }               
            }
            if(flag){
                listaUpd.add(acc);
            }            
        }   
        if(listaUpd!= null && listaUpd.size() > 0){
            update listaUpd;
        }
    }

    global void finish(Database.BatchableContext info){     
    	System.debug('fin');
    }
    
    //Flujo de creación de clientes en la unidad de crédito
    public static SL_Client_JSON ConsultaClienteSAP(String RutCode, String negocio) {
        SAP__mdt login = SAP__mdt.getInstance(negocio);
        
        SL_Login_JSON login_c = new SL_Login_JSON();
        if(!Test.isRunningTest()){
            login_c = LUREYE_Servicios_SAP.callLogin();
        }else{
            login_c = (SL_Login_JSON)JSON.deserialize('{"odata.metadata": "https://sap10.com:50001/b1s/v1/$metadata#B1Sessions/@Element","SessionId": "e413fb8e-61","Version": "1000190","SessionTimeout": 30}',SL_Login_JSON.class);
        }
        if(login_c!=null){
            String bodyjson =null;
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            HttpResponse response = new HttpResponse();
            request.setTimeout(120000);
            request.setEndpoint(login.Endpoint__c+'BusinessPartners(\'C'+RutCode+'\')');
            request.setMethod('GET');
            request.setHeader('Accept', '*/*');
            request.setHeader('Cookie', 'B1SESSION='+login_c.sessionId+'; ROUTEID=.node1');
        
            //System.debug('request: ' +request);
            response = http.send(request);      
            
            if(response.getStatusCode() == 200){
                //System.debug('Respuesta exitosa: '+response.getBody());
                system.debug('CLIENTE EXISTE');
                bodyjson = response.getBody().replace('"Currency"', '"Currencys"');
                SL_Client_JSON resp = (SL_Client_JSON)JSON.deserialize(bodyjson,SL_Client_JSON.class);
                LUREYE_Servicios_SAP.callLogout(login_c.sessionId);
                return resp;
            }else{
                SL_Client_Err_JSON failresp = (SL_Client_Err_JSON)JSON.deserialize(response.getBody(),SL_Client_Err_JSON.class);
                system.debug('CLIENTE NO EXISTE');
                system.debug('Mensaje desde SAP: '+failresp);
                LUREYE_Servicios_SAP.callLogout(login_c.sessionId);
                return null;
            }
        }
        return null;
    } 
    
    global void execute(SchedulableContext sc) {
        Lureye_ActualizaCuentasDesdeSAPBatch b = new Lureye_ActualizaCuentasDesdeSAPBatch();
        Id batchId2 = Database.executeBatch(b,1);
    }

}