force-app/main/default/objects/Account/fields/Condici_n_de_pago_EM__c.field-meta.xml
<CustomField>
    <fullName>Condici_n_de_pago_EM__c</fullName>
    <label>Condición de pago EM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30 días Precio Contado</fullName>
            </value>
            <value>
                <fullName>60 Días sin Intereses</fullName>
            </value>
            <value>
                <fullName>90 Días sin Intereses</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30 y 45 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 30% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 30% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40%, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40%, Cheques 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo contra entrega</fullName>
            </value>
            <value>
                <fullName>Anticipo 50%, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 50% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 50% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 50% saldo contra entrega</fullName>
            </value>
            <value>
                <fullName>Anticipo 60% saldo 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 70%, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 70%, Cheques 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 70%, Cheques 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Cheque adjunto 30, 60 y 90 días</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CondicionPago__c.field-meta.xml
<CustomField>
    <fullName>CondicionPago__c</fullName>
    <label>Condición de pago GE</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>30 días Precio Contado</fullName>
            </value>
            <value>
                <fullName>60 Días sin Intereses</fullName>
            </value>
            <value>
                <fullName>90 Días sin Intereses</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30 y 45 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, Cheques 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo, saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 20% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 30% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 30% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40%, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40%, Cheques 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 40% saldo contra entrega</fullName>
            </value>
            <value>
                <fullName>Anticipo 50%, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 50% saldo 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 50% saldo 60 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 50% saldo contra entrega</fullName>
            </value>
            <value>
                <fullName>Anticipo 60% saldo 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 70%, Cheques 30, 60 y 90 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 70%, Cheques 30 días</fullName>
            </value>
            <value>
                <fullName>Anticipo 70%, Cheques 30 y 60 días</fullName>
            </value>
            <value>
                <fullName>Cheque adjunto 30, 60 y 90 días</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RUT_SD__c.field-meta.xml
<CustomField>
    <fullName>RUT_SD__c</fullName>
    <label>RUT (sin dígito)</label>
    <precision>8</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <description>1, 2, 3 dependiendo del negocio (Generación, Electromecánica, etc.)</description>
    <label>Branch</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/RUT_SD__c.field-meta.xml
<CustomField>
    <fullName>RUT_SD__c</fullName>
    <description>Rut de usuario sin digito verificador</description>
    <inlineHelpText>Rut de usuario sin digito verificador</inlineHelpText>
    <label>RUT (Sin dígito)</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Lureye_ActualizaCuentaConSocioNegocioSAP.cls
public class Lureye_ActualizaCuentaConSocioNegocioSAP {
    
    @InvocableMethod
    public static void actualizarCondicionPagoCuenta(List<Id> ListIdCuenta){
        String idUsuario = UserInfo.getUserId();
        User currentUser = [SELECT Branch__c FROM User WHERE Id = :idUsuario LIMIT 1];
        system.debug('Branch usuario: ' + currentUser.Branch__c);
        integer branchCode = Integer.valueOf(currentUser.Branch__c.intValue());
        
        System.debug(ListIdCuenta);
        List<Account> listaCuentasUPD = new List<Account>();
        for(Id idCuenta: ListIdCuenta){
            Account acc = LUREYE_SAP_Controller.queryAccount(idCuenta);
            System.debug('CUenta->'+acc);
            if(acc != null){
                SL_Client_JSON socioNegocio = obtenerSocioNegocioSAP(acc);
                System.debug('socioNegocio->'+socioNegocio);
                if(socioNegocio != null){
                    List<Account> listaCuentas = obtenerCuentaUDP(acc, socioNegocio.paytermsgrpcode, branchCode);
                    System.debug('listaCuentas->'+listaCuentas);
                    if(listaCuentas != null && listaCuentas.size()>0){
                        listaCuentasUPD.addAll(listaCuentas);
                    }
                }
            }
        }

        if(listaCuentasUPD != null && listaCuentasUPD.size() > 0){
            System.debug('listaCuentasUPD->'+listaCuentasUPD);
            update listaCuentasUPD;
        }
    }
    
    public static SL_Client_JSON obtenerSocioNegocioSAP(Account acc){
        SL_Client_JSON socioNegocio = LUREYE_Servicios_SAP.ConsultaClienteSAP(String.valueof(acc.RUT_SD__c));
        return socioNegocio;
    }
    
    private static List<Account> obtenerCuentaUDP(Account acc, Integer condicionPago, integer branchCode){
        List<Account> listaCuentasUPD = new List<Account>();
        System.debug('acc.CondicionPago__c->'+acc.CondicionPago__c);
        System.debug('LUREYE_SAP_Controller.switchIntCondition(condicionPago)->'+LUREYE_SAP_Controller.switchIntCondition(condicionPago));
        
        if(branchCode == 1 && acc.CondicionPago__c != LUREYE_SAP_Controller.switchIntCondition(condicionPago)){
            acc.CondicionPago__c = LUREYE_SAP_Controller.switchIntCondition(condicionPago);
            listaCuentasUPD.add(acc);
        } else if(branchCode == 2 && acc.Condici_n_de_pago_EM__c != LUREYE_SAP_Controller.switchIntCondition(condicionPago) ) {
            acc.Condici_n_de_pago_EM__c  = LUREYE_SAP_Controller.switchIntCondition(condicionPago);
            listaCuentasUPD.add(acc);
        }	
                           
        return listaCuentasUPD;
    }
    
}